name: Make Executables
on:
  workflow_dispatch:
jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Create virtual environment
        shell: cmd
        run: |
          python -m venv venv
          venv\Scripts\python.exe -m pip install --upgrade pip
          venv\Scripts\python.exe -m pip install -r requirements.txt
          
      - name: Create windows executable
        shell: cmd
        run: |
           venv\Scripts\pyinstaller.exe Flare.spec --noconfirm
           echo "::debug::%CD%"
           
      - name: Upload windows executable folder as ZIP
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/Flare/

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: inno-script.iss

      - name: Upload windows installer as ZIP
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: Output/

  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Create virtual environment
        shell: bash
        run: |
          python -m venv venv
          venv/Scripts/python -m pip install --upgrade pip
          venv/Scripts/python -m pip install -r requirements.txt
          
      - name: Create linux executable
        shell: bash
        run: |
           venv/Scripts/pyinstaller Flare.spec --noconfirm
           echo "::debug::${PWD}"
           
      - name: Upload linux executable folder as ZIP
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: dist/Flare/

      # - name: Upload windows installer as ZIP
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: windows-installer
      #     path: Output/
